version: '2'
services:

  nodeapi:
    build: .
    image: barreiro/node-jaguer
    network_mode: bridge
    # command: yarn start
    command: yarn run compile
    ports:
      - "2525:80"
      - "9229:9229"
      - "27017:27017"
      