version: '2'
services:

  nodeapi:
    build: .
    dockerfile: Dockerfile-Production
    image: barreiro/node-jaguer
    # command: yarn start
    command: yarn run compile
    ports:
      - "2525:80"
      - "9229:9229"
