version: '2'
services:
  nginx:
    build: nginx/.
    image: barreiro/nginx
    ports:
      - "80:80"
    volumes:
      - ./ng-jaguer-madrid/dist:/usr/share/nginx/angular
    links:
      - nodeapi:nodeapi
      - angular:angular
    depends_on:
      - angular

  nodeapi:
    build: node-jaguer-madrid/.
    image: barreiro/node-jaguer
    # command: yarn start
    command: yarn run compile
    ports:
      - "2525:80"
      - "9229:9229"
    volumes:
      - ./node-jaguer-madrid/src:/usr/src/jaguer/src
      - ./node-jaguer-madrid/public:/usr/src/jaguer/public
    links:
      - mongo
    depends_on:
      - mongo